import { Ingradients } from "@/types/ingredient";

const IngradientList: Ingradients[] =[
  { "id": 1, "name": "Onion", "category": "vegetables" },
  { "id": 2, "name": "Tomato", "category": "vegetables" },
  { "id": 3, "name": "Garlic", "category": "vegetables" },
  { "id": 4, "name": "Ginger", "category": "vegetables" },
  { "id": 5, "name": "Green chili", "category": "vegetables" },
  { "id": 6, "name": "Potato", "category": "vegetables" },
  { "id": 7, "name": "Carrot", "category": "vegetables" },
  { "id": 8, "name": "Cauliflower", "category": "vegetables" },
  { "id": 9, "name": "Cabbage", "category": "vegetables" },
  { "id": 10, "name": "Spinach", "category": "vegetables" },
  { "id": 11, "name": "Fenugreek leaves", "category": "vegetables" },
  { "id": 12, "name": "Coriander leaves", "category": "vegetables" },
  { "id": 13, "name": "Curry leaves", "category": "vegetables" },
  { "id": 14, "name": "Brinjal", "category": "vegetables" },
  { "id": 15, "name": "Okra", "category": "vegetables" },
  { "id": 16, "name": "Bottle gourd", "category": "vegetables" },
  { "id": 17, "name": "Ridge gourd", "category": "vegetables" },
  { "id": 18, "name": "Bitter gourd", "category": "vegetables" },
  { "id": 19, "name": "Pumpkin", "category": "vegetables" },
  { "id": 20, "name": "Raw banana", "category": "vegetables" },
  { "id": 21, "name": "Green peas", "category": "vegetables" },
  { "id": 22, "name": "Drumstick", "category": "vegetables" },
  { "id": 23, "name": "Turnip", "category": "vegetables" },
  { "id": 24, "name": "Beetroot", "category": "vegetables" },
  { "id": 25, "name": "Radish", "category": "vegetables" },
  { "id": 105, "name": "Jackfruit", "category": "vegetables" },
  { "id": 106, "name": "Sweet potato", "category": "vegetables" },
  { "id": 107, "name": "Yam", "category": "vegetables" },
  { "id": 108, "name": "Colocasia", "category": "vegetables" },
  { "id": 109, "name": "French beans", "category": "vegetables" },
  { "id": 110, "name": "Cluster beans", "category": "vegetables" },
  { "id": 111, "name": "Snake gourd", "category": "vegetables" },
  { "id": 112, "name": "Amaranth leaves", "category": "vegetables" },
  { "id": 113, "name": "Pointed gourd", "category": "vegetables" },
  { "id": 114, "name": "Ivy gourd", "category": "vegetables" },
  { "id": 141, "name": "Bell Pepper (Capsicum)", "category": "vegetables" },
  { "id": 142, "name": "Cucumber", "category": "vegetables" },
  { "id": 143, "name": "Lemon Grass", "category": "vegetables" },
  { "id": 144, "name": "Mint leaves", "category": "vegetables" },
  { "id": 145, "name": "Spring Onion", "category": "vegetables" },

  { "id": 26, "name": "Basmati rice", "category": "grains_pulses" },
  { "id": 27, "name": "Parboiled rice", "category": "grains_pulses" },
  { "id": 28, "name": "Poha", "category": "grains_pulses" },
  { "id": 29, "name": "Sooji", "category": "grains_pulses" },
  { "id": 30, "name": "Wheat flour", "category": "grains_pulses" },
  { "id": 31, "name": "Maida", "category": "grains_pulses" },
  { "id": 32, "name": "Chickpeas", "category": "grains_pulses" },
  { "id": 33, "name": "Green gram", "category": "grains_pulses" },
  { "id": 34, "name": "Black gram", "category": "grains_pulses" },
  { "id": 35, "name": "Toor dal", "category": "grains_pulses" },
  { "id": 36, "name": "Masoor dal", "category": "grains_pulses" },
  { "id": 37, "name": "Rajma", "category": "grains_pulses" },
  { "id": 38, "name": "Kala chana", "category": "grains_pulses" },
  { "id": 39, "name": "Horse gram", "category": "grains_pulses" },
  { "id": 40, "name": "Sabudana", "category": "grains_pulses" },
  { "id": 115, "name": "Brown rice", "category": "grains_pulses" },
  { "id": 116, "name": "Jowar", "category": "grains_pulses" },
  { "id": 117, "name": "Bajra", "category": "grains_pulses" },
  { "id": 118, "name": "Ragi", "category": "grains_pulses" },
  { "id": 119, "name": "Moong dal", "category": "grains_pulses" },
  { "id": 120, "name": "Chana dal", "category": "grains_pulses" },
  { "id": 121, "name": "Barley", "category": "grains_pulses" },
  { "id": 122, "name": "Cornmeal", "category": "grains_pulses" },
  { "id": 146, "name": "Urad dal", "category": "grains_pulses" },
  { "id": 147, "name": "Millet", "category": "grains_pulses" },
  { "id": 148, "name": "Besan (Gram Flour)", "category": "grains_pulses" },
  { "id": 149, "name": "Sona Masoori rice", "category": "grains_pulses" },
  { "id": 150, "name": "Dalia (Broken Wheat)", "category": "grains_pulses" },

  { "id": 41, "name": "Chicken", "category": "meat_protein" },
  { "id": 42, "name": "Mutton", "category": "meat_protein" },
  { "id": 43, "name": "Fish", "category": "meat_protein" },
  { "id": 44, "name": "Eggs", "category": "meat_protein" },
  { "id": 45, "name": "Paneer", "category": "meat_protein" },
  { "id": 46, "name": "Tofu", "category": "meat_protein" },
  { "id": 47, "name": "Soya chunks", "category": "meat_protein" },
  { "id": 123, "name": "Prawns", "category": "meat_protein" },
  { "id": 124, "name": "Crab", "category": "meat_protein" },
  { "id": 125, "name": "Duck", "category": "meat_protein" },
  { "id": 151, "name": "Goat Meat", "category": "meat_protein" },
  { "id": 152, "name": "Quail", "category": "meat_protein" },

  { "id": 48, "name": "Cumin seeds", "category": "spices_whole" },
  { "id": 49, "name": "Coriander seeds", "category": "spices_whole" },
  { "id": 50, "name": "Mustard seeds", "category": "spices_whole" },
  { "id": 51, "name": "Fennel seeds", "category": "spices_whole" },
  { "id": 52, "name": "Fenugreek seeds", "category": "spices_whole" },
  { "id": 53, "name": "Carom seeds", "category": "spices_whole" },
  { "id": 54, "name": "Bay leaves", "category": "spices_whole" },
  { "id": 55, "name": "Cloves", "category": "spices_whole" },
  { "id": 56, "name": "Cinnamon stick", "category": "spices_whole" },
  { "id": 57, "name": "Green cardamom", "category": "spices_whole" },
  { "id": 58, "name": "Black cardamom", "category": "spices_whole" },
  { "id": 59, "name": "Black peppercorns", "category": "spices_whole" },
  { "id": 60, "name": "Star anise", "category": "spices_whole" },
  { "id": 61, "name": "Mace", "category": "spices_whole" },
  { "id": 62, "name": "Nutmeg", "category": "spices_whole" },
  { "id": 126, "name": "Saffron", "category": "spices_whole" },
  { "id": 127, "name": "Dried pomegranate seeds", "category": "spices_whole" },
  { "id": 153, "name": "Nigella seeds (Kalonji)", "category": "spices_whole" },
  { "id": 154, "name": "Dagad Phool (Black Stone Flower)", "category": "spices_whole" },
  { "id": 155, "name": "Poppy seeds (Khus Khus)", "category": "spices_whole" },

  { "id": 63, "name": "Red chili powder", "category": "spices_ground" },
  { "id": 64, "name": "Turmeric", "category": "spices_ground" },
  { "id": 65, "name": "Garam masala", "category": "spices_ground" },
  { "id": 66, "name": "Coriander powder", "category": "spices_ground" },
  { "id": 67, "name": "Asafoetida", "category": "spices_ground" },
  { "id": 68, "name": "Amchur powder", "category": "spices_ground" },
  { "id": 69, "name": "Kasuri methi", "category": "spices_ground" },
  { "id": 128, "name": "Cumin powder", "category": "spices_ground" },
  { "id": 129, "name": "Kashmiri chili powder", "category": "spices_ground" },
  { "id": 130, "name": "Black salt", "category": "spices_ground" },
  { "id": 156, "name": "Chaat Masala", "category": "spices_ground" },
  { "id": 157, "name": "Dry Ginger Powder (Sonth)", "category": "spices_ground" },
  { "id": 158, "name": "White Pepper Powder", "category": "spices_ground" },

  { "id": 70, "name": "Mustard oil", "category": "oils_fats" },
  { "id": 71, "name": "Groundnut oil", "category": "oils_fats" },
  { "id": 72, "name": "Sunflower oil", "category": "oils_fats" },
  { "id": 73, "name": "Ghee", "category": "oils_fats" },
  { "id": 74, "name": "Coconut oil", "category": "oils_fats" },
  { "id": 75, "name": "Vanaspati", "category": "oils_fats" },
  { "id": 131, "name": "Sesame oil", "category": "oils_fats" },
  { "id": 132, "name": "Olive oil", "category": "oils_fats" },
  { "id": 159, "name": "Rice Bran Oil", "category": "oils_fats" },

  { "id": 76, "name": "Salt", "category": "misc" },
  { "id": 77, "name": "Rock salt", "category": "misc" },
  { "id": 78, "name": "Tamarind", "category": "misc" },
  { "id": 79, "name": "Jaggery", "category": "misc" },
  { "id": 80, "name": "Sugar", "category": "misc" },
  { "id": 81, "name": "Vinegar", "category": "misc" },
  { "id": 82, "name": "Lemon", "category": "misc" },
  { "id": 83, "name": "Curd", "category": "misc" },
  { "id": 84, "name": "Fresh cream", "category": "misc" },
  { "id": 85, "name": "Coconut milk", "category": "misc" },
  { "id": 86, "name": "Milk", "category": "misc" },
  { "id": 87, "name": "Baking soda", "category": "misc" },
  { "id": 88, "name": "Baking powder", "category": "misc" },
  { "id": 89, "name": "Rava", "category": "misc" },
  { "id": 133, "name": "Honey", "category": "misc" },
  { "id": 134, "name": "Buttermilk", "category": "misc" },
  { "id": 135, "name": "Rose water", "category": "misc" },
  { "id": 136, "name": "Kewra water", "category": "misc" },
  { "id": 160, "name": "Green Cardamom Powder", "category": "misc" },
  { "id": 161, "name": "Paan (Betel Leaf)", "category": "misc" },
  { "id": 162, "name": "Edible Camphor", "category": "misc" },
  { "id": 163, "name": "Imli Paste (Tamarind Paste)", "category": "misc" },
  { "id": 164, "name": "Soya Sauce (often used in Indian-Chinese)", "category": "misc" },
  { "id": 165, "name": "Green Chili Sauce (often used in Indian-Chinese)", "category": "misc" },
  { "id": 166, "name": "Tomato Ketchup/Sauce", "category": "misc" },
  { "id": 167, "name": "Yeast", "category": "misc" },

  { "id": 90, "name": "Papad", "category": "pantry" },
  { "id": 91, "name": "Pickles", "category": "pantry" },
  { "id": 92, "name": "Mint chutney", "category": "pantry" },
  { "id": 93, "name": "Tamarind chutney", "category": "pantry" },
  { "id": 94, "name": "Coconut chutney", "category": "pantry" },
  { "id": 95, "name": "Sambar masala", "category": "pantry" },
  { "id": 96, "name": "Chole masala", "category": "pantry" },
  { "id": 97, "name": "Biryani masala", "category": "pantry" },
  { "id": 98, "name": "Dried red chilies", "category": "pantry" },
  { "id": 99, "name": "Almonds", "category": "pantry" },
  { "id": 100, "name": "Raisins", "category": "pantry" },
  { "id": 101, "name": "Cashews", "category": "pantry" },
  { "id": 102, "name": "Pistachios", "category": "pantry" },
  { "id": 103, "name": "Peanuts", "category": "pantry" },
  { "id": 104, "name": "Sesame seeds", "category": "pantry" },
  { "id": 137, "name": "Poppy seeds", "category": "pantry" },
  { "id": 138, "name": "Walnuts", "category": "pantry" },
  { "id": 139, "name": "Dried coconut", "category": "pantry" },
  { "id": 140, "name": "Vermicelli", "category": "pantry" },
  { "id": 168, "name": "Papadum", "category": "pantry" },
  { "id": 169, "name": "Sev", "category": "pantry" },
  { "id": 170, "name": "Boondi", "category": "pantry" },
  { "id": 171, "name": "Amla (Indian Gooseberry)", "category": "pantry" },
  { "id": 172, "name": "Charoli (Chironji)", "category": "pantry" },
  { "id": 173, "name": "Gulkand (Rose Petal Jam)", "category": "pantry" },
  { "id": 174, "name": "Silver Leaf (Chandi Vark)", "category": "pantry" }
]
export default IngradientList;